### ISSUE TITLE
Load Balancing is not normal

### ISSUE THREAD

**Issue by amg-web** [blindsidenetworks/scalelite#595] opened 2021-06-28 14:53 UTC
Since the new load balancing coalculation was introduced we experience issues with that.
All classes started simultaniously and after some of them devided evently on nodes, one node started to be overloaded.

Even in case you try to create meeting in a 15 min it will be again on same overloaded node.
The last time I changed polling interval to 10s, and the issue is again there.
![BigBlueButton All Servers - Grafana - Opera 28 06 2021 17_46_41](https://user-images.githubusercontent.com/22151881/123657711-b668f780-d839-11eb-8936-10bb48f7a353.png)
![BigBlueButton All Servers - Grafana - Opera 28 06 2021 17_34_07](https://user-images.githubusercontent.com/22151881/123657721-b832bb00-d839-11eb-83bd-3e37a76e69a9.png)

**Comment by amalrails** [comment] 2021-06-29 12:39
@amg-web are the `loadMultiplier` values for all servers same? Which version of SL are you using?

**Comment by amg-web** [comment] 2021-06-29 12:54
@amalrails
yes, all with default multiplier = 1.0
the problem started since new load balancing calculation.
Currently installed 1.1.4

**Comment by amalrails** [comment] 2021-06-29 13:49
@amg-web can you also pls share a screenshot post ` bundle exec rake servers` command

**Comment by amg-web** [comment] 2021-06-29 13:58
docker exec -it scalelite-api ./bin/rake servers
id: 91ce117e-e3e2-4c99-97ce-0213aab2daf7
        url: https://n3.jose.edu.py/bigbluebutton/api
        secret: tQWmiViGFijwUKxvYYBZvk0Fc3OFiWI73sbvSzNg5o
        enabled
        load: 15.0
        load multiplier: 1.0
        online
id: 11511754-f986-4ccc-adc1-df11e4155d19
        url: https://n2.ae.edu.py/bigbluebutton/api
        secret: Kx8uQ7VNyKSmztayvZ1OZBvC0nlQcjTfBnjiFNSSg
        enabled
        load: 88.0
        load multiplier: 1.0
        online
id: 989481df-938f-460f-bd3b-c958722e6e9b
        url: https://n4.apoe.edu.py/bigbluebutton/api
        secret: vTrG97uwmsPehFhf3j4ocWTPgB4kxIWuUFFJUR7IaM
        enabled
        load: 29.0
        load multiplier: 1.0
        online
id: 646b002d-8760-452a-ae38-bf4780683382
        url: https://n6.ase.edu.py/bigbluebutton/api
        secret: NZSRIsXJrjNuRyJImn0HRhdLljgky86v9TB2Ywcs
        enabled
        load: 90.0
        load multiplier: 1.0
        online
id: db03d83f-d175-46de-803a-46da65f03621
        url: https://n7.apsose.edu.py/bigbluebutton/api
        secret: SiQAoVdmU6pmhPuRpAVbD0Sj4DejnuvUIEshzBAo1ys
        enabled
        load: 23.0
        load multiplier: 1.0
        online
id: f770982f-598e-454c-a39f-7be50f835578
        url: https://n5.ape.edu.py/bigbluebutton/api
        secret: Zg5OvfFHtJ1YBuZnXkLtm1i96EvWiyLIi6Cg3uIzA
        enabled
        load: 78.0
        load multiplier: 1.0
        online
id: 7526c6c2-fc39-47d2-a3fd-23818838c08a
        url: https://n1.apoose.edu.py/bigbluebutton/api
        secret: vAsLbp5sf8J2AccqfkI7WWy1RlScC8oNho9r84AVHA
        enabled
        load: 187.0
        load multiplier: 1.0
        online

**Comment by amg-web** [comment] 2021-06-29 13:59
today n3 was with 10 rooms while others were less then 5

**Comment by amalrails** [comment] 2021-06-29 14:06
@amg-web thanks, will try to reproduce the same and update soon.

**Comment by amalrails** [comment] 2021-06-30 14:00
@amg-web i could not reproduce the issue, but i would like to get to the root of this problem, can you share your email?

**Comment by amalrails** [comment] 2021-06-30 14:01
> docker exec -it scalelite-api ./bin/rake servers
> id: 91ce117e-e3e2-4c99-97ce-0213aab2daf7
> url: https://n3.jose.edu.py/bigbluebutton/api
> secret: tQWmiViGFijwUKxvYYBZvk0Fc3OFiWI73sbvSzNg5o
> enabled
> load: 15.0
> load multiplier: 1.0
> online
> id: 11511754-f986-4ccc-adc1-df11e4155d19
> url: https://n2.ae.edu.py/bigbluebutton/api
> secret: Kx8uQ7VNyKSmztayvZ1OZBvC0nlQcjTfBnjiFNSSg
> enabled
> load: 88.0
> load multiplier: 1.0
> online
> id: 989481df-938f-460f-bd3b-c958722e6e9b
> url: https://n4.apoe.edu.py/bigbluebutton/api
> secret: vTrG97uwmsPehFhf3j4ocWTPgB4kxIWuUFFJUR7IaM
> enabled
> load: 29.0
> load multiplier: 1.0
> online
> id: 646b002d-8760-452a-ae38-bf4780683382
> url: https://n6.ase.edu.py/bigbluebutton/api
> secret: NZSRIsXJrjNuRyJImn0HRhdLljgky86v9TB2Ywcs
> enabled
> load: 90.0
> load multiplier: 1.0
> online
> id: db03d83f-d175-46de-803a-46da65f03621
> url: https://n7.apsose.edu.py/bigbluebutton/api
> secret: SiQAoVdmU6pmhPuRpAVbD0Sj4DejnuvUIEshzBAo1ys
> enabled
> load: 23.0
> load multiplier: 1.0
> online
> id: f770982f-598e-454c-a39f-7be50f835578
> url: https://n5.ape.edu.py/bigbluebutton/api
> secret: Zg5OvfFHtJ1YBuZnXkLtm1i96EvWiyLIi6Cg3uIzA
> enabled
> load: 78.0
> load multiplier: 1.0
> online
> id: 7526c6c2-fc39-47d2-a3fd-23818838c08a
> url: https://n1.apoose.edu.py/bigbluebutton/api
> secret: vAsLbp5sf8J2AccqfkI7WWy1RlScC8oNho9r84AVHA
> enabled
> load: 187.0
> load multiplier: 1.0
> online

@amg-web you can delete this comment

**Comment by amg-web** [comment] 2021-06-30 17:59
@amalrails yes a.gangan at gmail
here is fresh data. as you can see numer of rooms all time jumping to extreme 
![BigBlueButton All Servers - Grafana - Opera 30 06 2021 20_56_38](https://user-images.githubusercontent.com/22151881/124009238-08e71700-d9e6-11eb-8523-f4e4e5a21aeb.png)

**Comment by amalrails** [comment] 2021-07-06 13:26
closing this issue as it does not seem like a SL bug but more like a configuration issue. @amg-web will continue the debugging communication in our email thread.

**Closed by amalrails** 2021-07-06 13:26 UTC

**Comment by amg-web** [comment] 2021-07-06 13:31
> @amg-web you can delete this comment

deleted
