### ISSUE TITLE
scalelite-poller V1.1.1.0 crashes sometimes

### ISSUE THREAD

**Issue by playernine** [blindsidenetworks/scalelite#586] opened 2021-06-11 04:59 UTC
After the migration from scalelite v1.0.12.2 to v1.1.1.0

The scalelite-poller docker container crashes  sometimes. 

After that scalelite is unable to identify the correct nodes to start new meetings.

The effect was, that all Meetings startet on only 3 of 52 BBB nodes.

We are on the move from BBB 2.2.36 nodes to 2.3.3 nodes.

For exchange, we set the old nodes to condoned and if empty to disable.

After all recordings have been imported to scalelite we remove the 2.2.36 node.

After that we add a new node with the same URL, but changed secret. Still use the ramdom Server id's.

Once the poller crashes, the docker container stops and the systemd service changes to failed.

We can start the docker container via `systemctl start scalelite-poller ` and it seems to work.

The other three containers are still running and not directly affected.

Exception from syslog:

`Jun  8 06:36:22 bbb-scalelite1 docker[9879]: rake aborted!
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: ApplicationRedisRecord::ConcurrentModificationError: Servers list concurrently modified
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/app/models/server.rb:89:in `block (2 levels) in save!'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:2415:in `block in watch'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:69:in `block in synchronize'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:69:in `synchronize'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:2410:in `watch'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.1/lib/redis/namespace.rb:476:in `call_with_namespace'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.1/lib/redis/namespace.rb:352:in `block (2 levels) in <class:Namespace>'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/app/models/server.rb:73:in `block in save!'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/app/models/application_redis_record.rb:144:in `block in with_connection'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/lib/redis_store.rb:35:in `block in with_connection'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/lib/redis_store.rb:35:in `with_connection'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/app/models/application_redis_record.rb:143:in `with_connection'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/app/models/application_redis_record.rb:147:in `with_connection'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/app/models/server.rb:44:in `save!'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/lib/tasks/poll.rake:92:in `block (4 levels) in <main>'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promises.rb:1582:in `evaluate_to'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promises.rb:1765:in `block in on_resolvable'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promises.rb:1257:in `raise'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promises.rb:1257:in `wait_until_resolved!'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promises.rb:977:in `wait!'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: /srv/scalelite/lib/tasks/poll.rake:102:in `block (2 levels) in <main>'
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: Tasks: TOP => poll:all => poll:servers
Jun  8 06:36:22 bbb-scalelite1 docker[9879]: (See full trace by running task with --trace)`

**Comment by playernine** [comment] 2021-06-11 18:39
It happens very often, while removing server from the server list.

**Comment by wmchris** [comment] 2021-06-15 18:49
i can confirm this, but it happened when adding a server
```
D, [2021-06-14T06:35:08.515594 #7] DEBUG -- : Polling meetings
D, [2021-06-14T06:35:08.515926 #7] DEBUG -- : Polling servers
D, [2021-06-14T06:35:08.519328 #7] DEBUG -- : Polling Meeting id=pmly6ajhqpstbno8mf2ygo4ywgueapzhev9bbkxl on Server id=3f450969-57c8-45ed-90ad-f2406dd66008
D, [2021-06-14T06:35:08.519408 #7] DEBUG -- : Polling Server id=3f450969-57c8-45ed-90ad-f2406dd66008
D, [2021-06-14T06:35:08.519501 #7] DEBUG -- : Polling Server id=07be72b5-0e0e-4b21-8b37-c3415e832308
I, [2021-06-14T06:35:08.541050 #7]  INFO -- : Server id=07be72b5-0e0e-4b21-8b37-c3415e832308 online load: unavailable
rake aborted!
ApplicationRedisRecord::ConcurrentModificationError: Servers list concurrently modified
/srv/scalelite/app/models/server.rb:89:in `block (2 levels) in save!'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:2415:in `block in watch'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:69:in `block in synchronize'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:69:in `synchronize'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:2410:in `watch'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.1/lib/redis/namespace.rb:476:in `call_with_namespace'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.1/lib/redis/namespace.rb:352:in `block (2 levels) in <class:Namespace>'
/srv/scalelite/app/models/server.rb:73:in `block in save!'
/srv/scalelite/app/models/application_redis_record.rb:144:in `block in with_connection'
/srv/scalelite/lib/redis_store.rb:35:in `block in with_connection'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/srv/scalelite/lib/redis_store.rb:35:in `with_connection'
/srv/scalelite/app/models/application_redis_record.rb:143:in `with_connection'
/srv/scalelite/app/models/application_redis_record.rb:147:in `with_connection'
/srv/scalelite/app/models/server.rb:44:in `save!'
/srv/scalelite/lib/tasks/poll.rake:92:in `block (4 levels) in <main>'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promises.rb:1582:in `evaluate_to'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promises.rb:1765:in `block in on_resolvable'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promises.rb:1257:in `raise'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promises.rb:1257:in `wait_until_resolved!'
/srv/scalelite/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promises.rb:977:in `wait!'
/srv/scalelite/lib/tasks/poll.rake:102:in `block (2 levels) in <main>'
Tasks: TOP => poll:all => poll:servers
(See full trace by running task with --trace)
```

**Comment by jfederico** [comment] 2021-06-18 13:43
@wmchris and @playernine can you guys check the patch we put with v1.1.5-beta.1. Unfortunately we don't have a deployment with many BBB server to try it out with full load.

It that works, we'll push the release next week.

Thanks

**Comment by playernine** [comment] 2021-06-21 04:59
I still have an scalelite v1.1.1.0.

It has zero load, but I can reproduce the problem.

At start  Scalelite has one BBB 2.3.3 server.

If I add three  bbb Severs (2.3.1) scalelite crashes at the second or third add operation

I think it happens if the add command runs while the poller is doing a poll.

--------------------------------------------------------------------------------------------------

For testing v1.1.5-beta.1: I cannot install an beta on our live systems.

But I could clone one of my scalelites. 

They run inside an Ubuntu 18.04 LXC. 

On that cloned Scalelite, I cold run a few tests as described above

But I need to know, how to patch an scalelite with an beta image.

**Comment by wmchris** [comment] 2021-06-21 11:50
sadly i cant install the beta as well, as this is a productive system.

**Comment by jfederico** [comment] 2021-06-21 13:43
Well guys, this is the chicken and the egg game. If no one helps to test, then it will go as production either way as it is. Therefore you are going to need to install it. And if it fails, then you are going to complain the very next day. So, don't forget you had the chance :)

BTW. We encourage people to have a staging environment for serious deployments. You truly want to have that.

I am going to close this issue because I think we got it, but again, we'll see.

**Closed by jfederico** 2021-06-21 13:43 UTC

**Comment by playernine** [comment] 2021-06-21 14:50
> Well guys, this is the chicken and the egg game. If no one helps to test, then it will go as production either way as it is. Therefore you are going to need to install it. And if it fails, then you are going to complain the very next day. So, don't forget you had the chance :)
> 
> BTW. We encourage people to have a staging environment for serious deployments. You truly want to have that.
> 
> I am going to close this issue because I think we got it, but again, we'll see.

Did you read my  post? 
I don't know how install an beta release, but I would do it.
A hint could help.

But I can not test with users on it.

**Comment by EmmyGraugans** [comment] 2021-06-21 17:54
> Well guys, this is the chicken and the egg game.

I'm the (greylag) goose, would that help? ;)
Took me a while to find this ticket again, with it being closed now.

> I am going to close this issue because I think we got it, but again, we'll see.

I think you do – I tested it just now in my "play-scalelite", and it seems to work (it's hard to prove a negative, but I did my best).
- with 1.1.4, I could reproduce the problem (set POLL_INTERVAL=5, INTERVAL=5 – not sure which of these or if both are needed), removed five servers, added five servers, and the poller exited
- with 1.1.5-beta.1, I could NOT reproduce the problem, I even retried it afterwards with POLL_INTERVAL=1, INTERVAL=1 and again removing/adding five servers, and the poller remained stable.

As I said, it's not exactly proof, but it's at least something.

**Comment by EmmyGraugans** [comment] 2021-06-21 17:55
> I don't know how install an beta release, but I would do it.

It worked just as with a normal release: SCALELITE_TAG=v1.1.5-beta.1
(in case that helps for next time)

**Comment by playernine** [comment] 2021-06-22 03:19
> It worked just as with a normal release: SCALELITE_TAG=v1.1.5-beta.1
> (in case that helps for next time)

Thanks for the hint and the testing.

I would do the testing in a similar way.

**Comment by wmchris** [comment] 2021-06-22 10:00
> Well guys, this is the chicken and the egg game. If no one helps to test, then it will go as production either way as it is. 

i know this is not the ideal way, but remember, that the people maintaining the servers are most of the time not the people who make the rules. there are situations, where only software which went thru QA is allowed to be installed on a productive system.

I'm a little bit puzzled about the staging information, obviously i have a staging setup at hand, but from the information supplied earlier, this requires a system with high load?
