### ISSUE TITLE
Recording Playback return 404 not found from the Moodle recording link

### ISSUE THREAD

**Issue by COArikan** [blindsidenetworks/scalelite#405] opened 2021-01-26 17:58 UTC
Dear all, I have installed scalelite dockers and 5 BBB 2.3.4-dev servers with NFS structure.. 
https://myscalelite.address/bigbluebutton/api/ returns
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
<build>v1.0.8</build>
</response>

Everything seems work but in Moodle, after the meeting end, there's a problem with playback..
In the moodle recordings list, the link is similar to this one:
**https://myscalelite.address/playback/presentation/2.3/1ce896d8913ca7057f1792fbffe41757cad9f126-1611613827395**

I figured that, If I use this link with the recorded BBB address, I can show the recording playback:
**https://recorded-bbb.address/playback/presentation/2.3/1ce896d8913ca7057f1792fbffe41757cad9f126-1611613827395**

On the scalelite server, (both normal and also in from the docker sh):
root@bbblb:/var/bigbluebutton/published/presentation# **ls 1ce896d8913ca7057f1792fbffe41757cad9f126-1611613827395/**
captions.json  deskshare.xml  panzooms.xml  presentation_text.json  slides_new.xml
cursor.xml     metadata.xml   presentation  shapes.svg              video

As I seen in the docker shell, that presentation is available under /var/bigbluebutton/published folder..
But nginx doesn't reach it and also the 2.3 player is not available under /var/bigbluebutton/playback/presentation/ folder..  There are only 0.81  0.9.0  2.0 folders available..

I've made a trick and copy this folder to LOCAL FOLDER and bind mount from local folder.. Copied 2.0 to 2.3.. 
But moodle links are still not working..

I think scalelite-nginx container redirections have a problem but how can I resolve this issue?
scalelite-nginx docker **presentation.nginx** file is like this:
        location /playback/presentation/playback.html {
                return 301 /playback/presentation/2.0/playback.html?$query_string;
                #return 301 /playback/presentation/0.81/playback.html?$query_string;
                # If you have recordings from 0.9.0 beta versions and are sure
                # that you will never want to play recordings made with
                # BigBlueButton 0.81, comment the line above and uncomment the
                # following line:
                #return 301 /playback/presentation/0.9.0/playback.html?$query_string;
        }

        location /playback/presentation {
                root    /var/bigbluebutton;
                index  index.html index.htm;
        }

        location /presentation {
                root    /var/bigbluebutton/published;
                index  index.html index.htm;
        }

How can I convert my links to work playback?
Thanks..

**Comment by COArikan** [comment] 2021-01-29 01:04
Hi again,
I think I found the problem...
In the container, nginx use the root directory: /var/lib/nginx/html but the recordings root is /var/bigbluebutton...
I can link /var/lib/nginx/html to /var/bigbluebutton and it starts working, but when the services restart, it resets everything..
I think I form all the branch and fix them and use my fork??

I can also redirect nginx requests to other bbb machine and manage to work.. But it is not a good solution..

Is there anyway to fix this issue?

**Comment by jfederico** [comment] 2021-02-26 15:46
The issue is that there is no support for BBB 2.3 recordings just yet. See #416

**Comment by jfederico** [comment] 2021-04-01 15:34
This change is planned for v1.1 and further, but there are extended images for 1.0 as 1.0.12.1. This is the way it will be done until 2.3 is released as stable.

You guys can try using one of the new extended images by editing your `/etc/default/scalelite` file, like this:

SCALELITE_REPO=blindsidenetwks
SCALELITE_TAG=v1.0.12.1-bionic230-amazonlinux

SCALELITE_REPO=blindsidenetwks
SCALELITE_TAG=v1.0.12.1-bionic230-alpine

**Closed by jfederico** 2021-04-01 15:34 UTC
Labels: v1.1

**Comment by emostoyanov** [comment] 2021-05-08 22:38
If you are running scalelite as per [https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6](https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6) you can solve this situation temporarily (until  v1.1 is ready) by adding nginx redirect. Execute a schell in the scalelite-nginx container 

`docker exec -it scalelite-nginx sh
`

and add a file

`
/etc/bigbluebutton/nginx/playback.html
`

with the following content:

```
location /playback/presentation/2.3 {
  rewrite ^/playback/presentation/2.3(.*)$ /playback/presentation/2.0/playback.html?meetingId=$1 permanent;
}
```

Test with nginx -t, exit the container shell and restart 

`docker stop scalelite-nginx && docker start scalelite-nginx
`

Of course in this way the new BBB 2.3 player will be used, but at least the recordings will be accessible from Moodle.
