### ISSUE TITLE
<greenlight>/admin/room Invalid BigBlueButton Endpoint and Secret

### ISSUE THREAD

**Issue by lookas1** [blindsidenetworks/scalelite#89] opened 2020-03-22 11:57 UTC
We have setup Greenlight frontend pointing to our Scalelite load balancer. Load balancing is working fine and we are able to create sessions on particular servers under LB. However there is an interesting issue. We have 3 servers under LB as per:

$ docker exec -it scalelite-api bin/rake servers
id: e2de6ff5-6955-48ab-9223-3521ced972cc
        url: https://<server1>/bigbluebutton/api
        secret: secret1
        enabled
        load: unavailable
        offline
id: 5a85d300-85be-4f63-9abf-244e6efe18e2
        url: https://<server1>/bigbluebutton/api
        secret: secret2
        enabled
        load: 0.0
        online
id: 56bd3e1e-5051-4d52-b532-53faa2515bd1
        url: https://<server1>/bigbluebutton/api
        secret: secret3
        enabled
        load: 0.0
        online

So as per above server1 is down, server2, server3 are up. With such greenlight while clicking Meeting Rooms we are getting: Invalid BigBlueButton Endpoint and Secret.

in LB logs I can see:

I, [2020-03-22T11:06:22.285650 #6]  INFO -- : [b274ee57-e874-429e-841e-01339e566c9c] Started GET "/bigbluebutton/api/getMeetings?checksum=f6a8f514c05306ae634616879116f3245d459dbb" for <LB_IP> at 2020-03-22 11:06:22 +0000
I, [2020-03-22T11:06:22.286693 #6]  INFO -- : [b274ee57-e874-429e-841e-01339e566c9c] Processing by BigBlueButtonApiController#get_meetings as XML
I, [2020-03-22T11:06:22.286769 #6]  INFO -- : [b274ee57-e874-429e-841e-01339e566c9c]   Parameters: {"checksum"=>"f6a8f514c05306ae634616879116f3245d459dbb"}
W, [2020-03-22T11:06:32.290600 #6]  WARN -- : [b274ee57-e874-429e-841e-01339e566c9c] Error execution expired accessing server e2de6ff5-6955-48ab-9223-3521ced972cc.

It looks like scalelite is trying to get server meetings from offline server. The same error is when server1 is disabled.

Error is gone when we remove server from LB. 

I find it as an issue as LB is reporting online/offline status so should probably not to try getting meeting rooms from offline servers

**Comment by lookas1** [comment] 2020-03-23 10:01
I think the issue is more severe than initially thought. Servers offline in disabled status make greenlight throw same errors on the home page. It seems we need to remove offline servers manually from Scalelite to make cluster work.

**Comment by farhatahmad** [comment] 2020-03-23 19:25
Hi @lookas1,

Thanks for reporting this. I've located the cause and am working on the fix for this issue.

**Comment by lookas1** [comment] 2020-03-23 19:40
@farhatahmad thanks for taking a look into it. We really appreciate your work around scalelite. Do you think it would be possible to return rake:servers details in XML or JSON so we could parse it for automated hosts add/remove process?  Is there any switch or anything like that to set output format?

**Comment by farhatahmad** [comment] 2020-03-23 20:55
@lookas1 It's definitely possible, but not at the moment. At the moment it just prints directly to the console.

**Comment by lookas1** [comment] 2020-03-24 10:08
@farhatahmad if you can point me the file this issue is located in maybe I could help you fixing it.

**Comment by farhatahmad** [comment] 2020-03-24 13:58
https://github.com/blindsidenetworks/scalelite/blob/v1/lib/tasks/servers.rake#L4

That's the rake server task that prints out the list of servers

**Comment by iceraven721** [comment] 2020-03-25 23:14
Thanks for posting this.  I eagerly await the fix as I was seeing the same issue when I turned off instances in the pool.

**Comment by farhatahmad** [comment] 2020-03-26 18:30
@iceraven721 The rake status task is a separate issue which I've fixed with this [PR](https://github.com/blindsidenetworks/scalelite/pull/102)

**Comment by iceraven721** [comment] 2020-03-26 19:25
@farhatahmad Ah ok.  Wasn't sure if it was related since I was having the same issue as this thread.  What's the best method to update the new files on the live environment?

Thanks

**Comment by farhatahmad** [comment] 2020-03-26 19:34
@iceraven721 You can't update until we release a new version. Once we do, we'll post an announcement with the new features and the instructions to update

**Comment by iceraven721** [comment] 2020-03-26 20:27
@farhatahmad Ah ok. Sounds good.

**Closed** 2020-05-01 18:10 UTC
Labels: bug
