### ISSUE TITLE
get_meetings issue when a server is manually disabled

### ISSUE THREAD

**Issue by thijs-sebsoft** [blindsidenetworks/scalelite#500] opened 2021-03-23 08:11 UTC
When manually shutting down a server and then calling the "get_meetings" action.
After that scalelite will return an with an error 500.
This is because the code does not account for disabled servers.

**Comment by PhMemmel** [comment] 2021-03-23 08:14
Probably duplicate of #498 ?

In this case: You need to wait for the poller to update the online/offline state of the bbb server. After that getMeetings works again. Workaround would be: trigger polling action on scalelite immediately after shutting down a bbb node.

**Comment by systems-levigo** [comment] 2021-03-23 12:31
I think we got the same issue here.
I set one of our bbb servers to disabled.
``./bin/rake status`` is now showing:
```
  STATE   STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS 
  disabled  online         0                      0                0                                0 
```
But meetings are running on this server.
No change after ``./bin/rake poll:all``

**Comment by amalrails** [comment] 2021-03-23 20:22
@systems-levigo have you tried the servers:panic option instead of servers:disable?

**Comment by systems-levigo** [comment] 2021-03-24 08:43
I haven't tried it yet.

> Disable a server and clear all meeting state. This method is used to recover from a crashed BigBlueButton server. After the meeting state is cleared, anyone who tries to join a meeting that was previously on this server will instead be directed to a new meeting on a different server.

Sounds like all running meetings will be terminated or am I wrong?

**Comment by amalrails** [comment] 2021-03-24 13:01
> I haven't tried it yet.
> 
> > Disable a server and clear all meeting state. This method is used to recover from a crashed BigBlueButton server. After the meeting state is cleared, anyone who tries to join a meeting that was previously on this server will instead be directed to a new meeting on a different server.
> 
> Sounds like all running meetings will be terminated or am I wrong?

yes all the meetings from that server will be deleted.

**Comment by systems-levigo** [comment] 2021-03-25 08:48
Yeah, this it not an option then.
Two releases ago, deactivating a server still worked.

**Comment by jfederico** [comment] 2021-03-25 14:19
Yeah, 2 releases ago was working for your use case because there was a bug.

When you disable the server you are decommissioning that server. SL should ignore it. That was the expected behaviour, but, it was still polling, (that is the bug), causing the poller to fail when the BBB servers were down.

So, in all case this is a new feature request where probably there is new rake task for doing this type of polling, or, we add a modifier so (ENV variable) you use it one way or the other.

**Comment by jfederico** [comment] 2021-03-25 14:56
This is actually two issues in one. It is a bug because there should not be a 500 error, but also a feature request for what the polling of disabled servers means.

The former should be corrected asap. I think @amalrails can have an answer for that soon and be released as a patch. But the later we are exploring one more possibility. It may go until the next minor release (1.1).

**Comment by systems-levigo** [comment] 2021-03-26 08:13
Thank you for the clarification.
What is the right way to put a server on maintenance at the moment if the server is still in use?

**Closed** 2021-03-26 13:56 UTC
Labels: bug, feature request

**Comment by jfederico** [comment] 2021-03-26 14:25
> What is the right way to put a server on maintenance at the moment if the server is still in use?

Unfortunately, the only way is to disable the server all at once, but as you know it will put it out of the poller too.

How often are you putting the server in maintenance though? We are considering adding a new state, but before doing that, would you mind elaborating on your use case. I would like to make sure we are covering it.

**Comment by systems-levigo** [comment] 2021-03-26 15:23
Our usecase is the following:
When a new BBB version is released, we are testing it on a different server (no cluster).
If everything is OK, we will deploy the update to the bbb cluster servers one by one.
We only deactivate the "maintenance server" and the other BBB servers continue to run.
For example disabling the "maintenance server" at 3 pm and upgrading it at 6 pm -> All ongoing sessions have been closed by the users.
