### ISSUE TITLE
Scalelite: Nginx - Connection refused

### ISSUE THREAD

**Issue by Marco-Total** [blindsidenetworks/scalelite#845] opened 2022-11-22 08:24 UTC
Hello together,

we are facing the problem that since yesterday our scalelite server has stopped working.

We have not installed any updates. The Lets Encrypt certificate is still valid for one month.

When trying to call the API we get a Refused:

```
root@cmpvideolb:/etc/systemd/system# curl https://videolb.cmp.de/bigbluebutton/api
curl: (7) Failed to connect to videolb.cmp.de port 443: Connection refused
```

The three Docker containers (NGINX, API, POLLER) started fine:
```
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
f47bd4baad79 blindsidenetwks/scalelite:v1.3.5-nginx "/etc/nginx/start -g..." 30 minutes ago Up 30 minutes 111.11.111.111:80->80/tcp, 111.11.111.111:443->443/tcp scalelite- nginx
af8b627c4a80 blindsidenetwks/scalelite:v1.3.5-poller "bin/start-poller" 54 minutes ago Up 54 minutes scalelite-poller
d61577319eab blindsidenetwks/scalelite:v1.3.5-api "bin/start" 54 minutes ago Up 54 minutes 3000/tcp scalelite-api
```

In docker log I can see that a file "/etc/nginx/conf.d/scalelite.template" is missing:
```
root@cmpvideolb1:/etc/systemd/system# docker logs f47bd4baad79
Startup script was run as init, re-executing using tini.
Generating templated nginx configuration...
Using non-SSL configuration template.
**/etc/nginx/start: line 32: can't open /etc/nginx/conf.d/scalelite.template: no such file**
Starting nginx periodic reload process...
Starting nginx...
root@cmpvideolb1:/etc/systemd/system#
```

In the docker directoy i can't find a folder "conf.d"
```
root@cmpvideolb1:/etc/systemd/system# docker exec -it f47bd4baad79 ls /etc/nginx
dhparam.pem     http.d          nginx.conf      start
fastcgi.conf    mime.types      scgi_params     uwsgi_params
fastcgi_params  modules         ssl
```

The systemd on my server looks like this:
```
root@cmpvideolb1:/etc/systemd/system# cat /etc/systemd/system/scalelite-nginx.service
[Unit]
Description=Scalelite Nginx
After=network-online.target
Wants=network-online.target
Before=scalelite.target
PartOf=scalelite.target
After=scalelite-api.service
Requires=scalelite-api.service
After=remote-fs.target
[Service]
EnvironmentFile=/etc/default/scalelite
ExecStartPre=-/usr/bin/docker kill scalelite-nginx
ExecStartPre=-/usr/bin/docker rm scalelite-nginx
ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx
ExecStart=/usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 111.11.111.111:80:80 --publish 111.11.111.111:443:443 --mount type=bind,source=${SCALELITE_RECORDING_DIR}/published,target=/var/bigbluebutton/published,readonly $SCALELITE_NGINX_EXTRA_OPTS blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx
ExecStartPost=/usr/bin/docker image prune -f
[Install]
WantedBy=scalelite.target
root@cmpvideolb1:/etc/systemd/system#
```

The configuration file for the Scalelite Docker looks like this:
```
root@cmpvideolb1:/etc/systemd/system# cat /etc/default/scalelite
URL_HOST=videolb.cmp.de
SECRET_KEY_BASE=xxx
LOADBALANCER_SECRET=xxx
DATABASE_URL=postgresql://scalelite:xxx@192.168.100.10/scalelite
REDIS_URL=redis://:xxx@192.168.100.10

SCALELITE_TAG=v1.3.5
SCALELITE_RECORDING_DIR=/var/local/bbb

NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly

RECORDING_DISABLED=true
RECORDING_IMPORT_POLL=false
root@cmpvideolb1:/etc/systemd/system#
```

Can anyone help me, i have no idea, how i can solve the problem.

Thanks!
Marco

Marco

**Comment by schorschroch** [comment] 2022-11-22 08:28
Hello all,
Same issue here since 1.3.5 release.
Switching back to 1.3.4 was our workaround.

Bernhard

**Comment by Bevito** [comment] 2022-11-22 22:43
Hi, 
Same here.  I'll followed Bernhard advice and I rolled back to 1.3.4 too.
I hope an update or a patch will be out soon.
Best regards.

**Comment by flyinghuman** [comment] 2022-11-25 06:30
same here. please fix this. we also rolled back for the moment.

**Comment by marmaou** [comment] 2022-11-26 09:14
Folder /etc/nginx/http.d is empty. File /etc/nginx/start still refers to missing folder /etc/nginx/conf.d. Moreover, the missing file /etc/nginx/conf.d/scalelite.template has references to the missing folder. Actually, the same is true for all file in the original /etc/nginx/conf.d folder.

**Comment by dannyplace** [comment] 2022-11-27 19:30
Same problem here, switched back to 1.3.4

**Comment by NiTRoeSE** [comment] 2022-11-28 08:50
Same here, switched back to 1.3.4

**Comment by debuglevel** [comment] 2022-11-28 09:42
Does this software have any basic automated integration tests? As far as I see, this would be as simple as "connects to port 80".

**Comment by defnull** [comment] 2022-11-28 09:48
Docker based deployments are not tested prior a release apparently. This is not the first time a new release breaks things unfortunately, so we started maintaining our own fork and usually wait a couple of days after each release to be sure to not break things in production.

**Comment by jfederico** [comment] 2022-11-28 10:34
@defnull, with all due respect, that is a very blunt statement, since you are not part of the people doing the releases or development. 

The images are tested and used in several deployments before release. Demo is one of them (although very different as it runs on kubernetes and the front-end proxy is not the image by default). But as you may know there are many ways of deploying SL, and yes, the tests we run this time did not cover the systemd deployment. But keep in mind that we support several versions, several images, and several deployments.

If you want to get involved though, you are welcome to join us. I am sure this project will be better with your help. Ping me privately when you have a chance.

Now, to everybody else. Before being released as "stable" (which is the more stable we can get it), it is available at least for 2 weeks as beta. We ask our customers and close contributors (with whom we maintain a close and friendly relationship since the inception of SL) to test their own deployment. We fix what is reported, and then we release.

But, if nobody in the (free and open source) community try it out and wait until is tagged as "stable", then these situations happen.

So again, why don'y instead of waiting to see if nothing breaks after it is released as "stable", you do the same with the beta.1 release? you are doing it anyways. That would help everybody.

**Comment by jfederico** [comment] 2022-11-28 10:35
Anyways, at a first glance this seems to be the cuplit after the update of base alpine imag https://github.com/blindsidenetworks/scalelite/commit/f71012d1cc53bd3bea5c2dc444ed89ebc701a70f#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L32

Patch is on the way

**Closed** 2022-11-28 10:47 UTC

**Comment by dirk-hl** [comment] 2022-11-28 14:23
Hello, the error is not fixed in version 1.3.5.1. I get the following error message:
Startup script was run as init, re-execing using tini.
Generating templated nginx configuration...
Using SSL configuration template.
/etc/nginx/start: line 32: can't open /etc/nginx/conf.d/scalelite-ssl.template: no such file
Starting nginx periodic reload process...

The conf.d directory is missing, there is only http.d.

**Comment by defnull** [comment] 2022-11-28 14:52
Yes, the startup script still assumes config is in the `conf.d` instead of the `http.d` directory. The fix was incomplete.

**Comment by marmaou** [comment] 2022-11-28 15:03
I think that the command in line 33 (that was deleted) "# RUN ln -s /etc/nginx/http.d/ /etc/nginx/conf.d" is needed.

**Comment by defnull** [comment] 2022-11-28 15:10
That line was just a comment in the original Dockerfile and had no effect. I assumed that the startup script was already updated accordingly, but it was not. So, there were two bugs and my PR fixed only one of them. Another release I guess.

**Comment by jfederico** [comment] 2022-11-29 13:57
@Marco-Total @dirk-hl I tried to contact you but I could not find your emails or social accounts.

Would you mind trying the images for `[v1.3.5.2-beta.1]`. It comes with just a mockey-patch but, the focus right now is to get you back up and running with the newest code.

Bottom line, my recommendation would be for you to move away from the systemd deployment (It will go away in the next major release along with the custom image for nginx, the poller and the recordng-importer image).

Also, a better way to implement the front-end proxy is to use an stock nginx image. That way you are not dependent of changes such as this. You can check the scripts for the docker-compose deployment `v2`. That is the way we have been recommending people to do deployments for quite a while.

**Comment by dirk-hl** [comment] 2022-11-29 14:31
Version v1.3.5.2-beta.1 works again. Thx.

I have installed with your Docker instructions: https://github.com/blindsidenetworks/scalelite/blob/master/docker-README.md
Is there a migration path to a docker-compose deployment?

**Comment by marmaou** [comment] 2022-11-29 14:53
I confirm, that it works again.

**Comment by jfederico** [comment] 2022-11-29 15:12
Superb! Thanks for trying it out @dirk-hl and @marmaou .

Now @dirk-hl, the deployment itself. Yes, I know, that is the "official" deployment. And "officially" I have to tell you that it works :sweat_smile: The problem is that the `systemd` deployment it is, let us say, a little more difficult to setup and maintain. It requires full understanding of the components and the way they are connected.

And since you are asking for directions, I am going to assume that you would rather have a step-by-step guide to follow than figuring all things out yourself.

It is OK. Many of the developers we have had (working on SL) over the years still complain about its complexity.

And no, there is no documentation for such migration. But I wrote an article a while back to make sysadmins life easier. See: [Scalelite Lazy Deployment](https://medium.com/@JesusFederico/scalelite-lazy-deployment-e3cd0af76d39) and [Scalelite Lazy Deployment - Part II](https://medium.com/@JesusFederico/scalelite-lazy-deployment-part-ii-240ffddfbbf5)

It can be argued that it is not the best for production (I never said it was), but it at least give you something you may be more familiar with (or you will be soon enough).

There is more coming. You can find out [here](https://medium.com/@JesusFederico/scalelite-deployments-in-a-right-way-part-i-8f5df343a62d) what my personal plans are.

In terms of the plans for the project, we should be making an official publication soon.

Meanwhile, I can tell you help with Documentation and Community Support and Testing is highly appreciated.

I hope this helps, or at least gives you some clues on how to address it.

**Comment by dannyplace** [comment] 2022-11-30 09:08
Also I can confirm the fix does the job.
