### ISSUE TITLE
post_publish_scalelite.rb is not working

### ISSUE THREAD

**Issue by makabar** [blindsidenetworks/scalelite#474] opened 2021-03-03 13:26 UTC
Dear @jfederico 

bbb-record --list says

`● bbb-rap-resque-worker.service - BigBlueButton resque worker for recordings
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-resque-worker.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-03-03 14:11:25 CET; 4min 13s ago
 Main PID: 21364 (sh)
    Tasks: 7 (limit: 4915)
   CGroup: /system.slice/bbb-rap-resque-worker.service
           ├─21364 /bin/sh -c /usr/bin/rake -f ../Rakefile resque:workers >> /var/log/bigbluebutton/bbb-rap-worker.log
           ├─21371 /usr/bin/ruby /usr/bin/rake -f ../Rakefile resque:workers
           └─21755 resque-2.0.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:captions

Mar 03 14:15:18 bbb2 bbb-rap[23371]: Success?: false
Mar 03 14:15:18 bbb2 bbb-rap[23371]: Process exited? true
Mar 03 14:15:18 bbb2 bbb-rap[23371]: Exit status: 1
Mar 03 14:15:18 bbb2 bbb-rap[23371]: Post publish script /usr/local/bigbluebutton/core/scripts/post_publish/post_publish_scalelite.rb/post_publish_scalelite failed
Mar 03 14:15:18 bbb2 bbb-rap[23371]: Task: Getting external meeting id
Mar 03 14:15:18 bbb2 bbb-rap[23371]: Task: Getting meeting metadata
Mar 03 14:15:18 bbb2 bbb-rap[23371]: Ended worker publish for 6b1f0ca342544b65b005e60287ad6cd6cc559a4a-1614777251782 with result true
Mar 03 14:15:18 bbb2 bbb-rap[23371]: Scheduling next step for publish
Mar 03 14:15:18 bbb2 bbb-rap[23371]: No next step for publish, will not schedule anything
Mar 03 14:15:18 bbb2 bbb-rap[23371]: done: (Job{rap:publish} | BigBlueButton::Resque::PublishWorker | [{"meeting_id"=>"6b1f0ca342544b65b005e60287ad6cd6cc559a4a-161…esentation"}])
Hint: Some lines were ellipsized, use -l to show in full.`

it seems that the ruby script cannot fetch the meeting_id

`/usr/local/bigbluebutton/core/scripts/post_publish/post_publish_scalelite.rb:48:in `<main>': Meeting ID was not provided (RuntimeError)`

tested on BBB 2.3-dev alpha 7

**Comment by jfederico** [comment] 2021-03-03 15:41
You are working with BBB 2.3 and recordings for 2.3 are not yet supported.

You may want to take a look to this PR https://github.com/blindsidenetworks/scalelite/pull/459, which is not going to be merged as is, but just to give you an idea of what you have to change.

The issue is that 2.3 is still in active development and not all the formats are yet implemented. We can not make this part of the images for production

**Closed by jfederico** 2021-03-03 15:41 UTC

**Comment by makabar** [comment] 2021-03-03 15:43
Thx for reply.
best regards

**Comment by freehussain** [comment] 2023-10-10 13:45
hello,

it still exist, i'm working on bigbluebutton 2.7.1

**Comment by freehussain** [comment] 2023-10-10 13:45
root@asuvcr:/usr/local/bigbluebutton/core/scripts/post_publish# sudo -n -u bigbluebutton -g scalelite-spool ruby ./scalelite_post_publish.rb
Recording transferring to Scalelite starts
Meeting ID was not provided
Transferring recording for  to Scalelite
Found recording format: presentation/
Creating recording archive
Transferring recording archive to /mnt/scalelite-recordings/var/bigbluebutton/spool
.tar

sent 368,805 bytes  received 35 bytes  737,680.00 bytes/sec
total size is 368,640  speedup is 1.00
Create sender.done file
Recording transferring to Scalelite ends
