### ISSUE TITLE
Scalelite forgots BBB-Instances

### ISSUE THREAD

**Issue by bernxa** [blindsidenetworks/scalelite#366] opened 2020-11-10 09:25 UTC
On two consecutive days I noticed that Scalelite "forgot" the instances I added with ./bin/rake servers:add and activated with ./bin/rake servers:enable. A query of ./bin/rake status showed me that no more BBB instances were stored.

I followed the readme.md in this repository. In the logs I could not find anything usable via docker logs scalelite-api.

Does anyone else know this behavior? How can I turn it off?

**Comment by matiasilva** [comment] 2020-11-10 12:11
Definitely a duplicate of other issues.

**Closed** 2020-11-10 14:03 UTC

**Comment by bernxa** [comment] 2020-11-10 18:42
Duplicate of an other issue? If so, I apologize. But please link me to the other error so I can read what it is and how I solve the problem.
