### ISSUE TITLE
How to enable recording automatic deletion on the BigBlueButton server

### ISSUE THREAD

**Issue by xscharlie** [blindsidenetworks/scalelite#168] opened 2020-04-22 04:07 UTC
In this section [configuring-the-bigbluebutton-recording-transfer](https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#configuring-the-bigbluebutton-recording-transfer) says:

> Once the recording transfer has been tested, you can optionally enable recording automatic deletion on the BigBlueButton server to remove the local copies of the recordings and free up disk space.

How I do that, is there a way to perform that from scalelite server or it's necesary do it from bbb server?

**Comment by SebastianZiegler** [comment] 2020-04-24 14:40
you do this on each bbb server, see /etc/cron.daily/bigbluebutton there it is prepared you only have to uncomment it

**Comment by farhatahmad** [comment] 2020-04-24 17:48
`/etc/cron.daily/bigbluebutton` will only delete the raw recording files. I'm working on including that cron job that deletes the recordings in this repo

**Comment by duduribeiro** [comment] 2020-04-26 00:14
@farhatahmad do you have some tip or script that I can also purge old files from the shared drive?
thanks

**Comment by Cistoge** [comment] 2020-05-23 08:20
I had asked the same question in another issue which has been closed now as a duplicate of this one. In the meanwhile, I found this script

https://docs.bigbluebutton.org/2.2/customize.html#delete-recordings-older-than-n-days

which can be used to delete recordings older then MAXAGE days from the BigBlueButton server.

**Comment by systems-levigo** [comment] 2021-01-25 11:53
> `/etc/cron.daily/bigbluebutton` will only delete the raw recording files. I'm working on including that cron job that deletes the recordings in this repo
Are you still working on this feature?
We need to remove the recordings from our NFS server and scalelite database with a cronjob.

**Comment by netzwerk-azv** [comment] 2021-02-01 22:37
> 
> A delete cronjob with "endtime older than X days" and a "find in `/mnt/scalelite-recordings/var/bigbluebutton/published/presentation/`" should do the job.
> 
> EDIT2:
> Tested and it seems to work. Please correct me if I have forgotten something.

Would you be so kind to share your script if thats possible?
The script that deletes (in the correct way) recordings on -scalelite- server older than x-days. From what I understand I need one on scalelite too (because after they are copied to scalelite-server I can delete them in BBB and they still exist in scalelite).

**Comment by systems-levigo** [comment] 2021-02-02 08:05
@netzwerk-azv sure.

We got that script on our scalelite (not productive right now):
``
#!/bin/bash

MAXAGE=7
LOGFILE=/var/log/bbb-recording-cleanup-nfs.log

echo "$(date --rfc-3339=seconds) Deleting recordings older than ${MAXAGE} days" >>"${LOGFILE}"
sudo -u YOUR-USER find /mnt/scalelite-recordings/var/bigbluebutton/published/presentation/ -maxdepth 1 -type d -mtime +$MAXAGE -exec rm -rf '{}' +

su -c "psql -d scalelite -c \"delete from playback_formats where id in(select id from recordings where endtime < NOW() - INTERVAL '$MAXAGE days')\"" postgres
su -c "psql -d scalelite -c \"delete from thumbnails where playback_format_id in(select id from recordings where endtime < NOW() - INTERVAL '$MAXAGE days')\"" postgres
su -c "psql -d scalelite -c \"delete from recordings where id in(select id from recordings where endtime < NOW() - INTERVAL '$MAXAGE days')\"" postgres
``
No error handling, no correct logging. Feel free to improve it and reshare.

**Comment by hmahdi-s** [comment] 2021-02-02 21:02
@netzwerk-azv 
could you please describe where should use this script?
 which directory in scalelite server?

**Comment by hmahdi-s** [comment] 2021-02-04 06:21
@farhatahmad 
Did you achieve for auto delete from scalelite server?

**Comment by uzeportal** [comment] 2021-07-21 21:47
Did you figure out how to delete the recordings automatically?

**Comment by hmahdi-s** [comment] 2021-07-22 06:37
@uzeportal 
unfortunately I didn't.  now i use bbb api for deleting by running manually or as cron.

**Comment by uzeportal** [comment] 2021-07-22 13:38
Are you deleting records individually on each BBB server? Or are you deleting it from the scalelite server? Can you share the cron code that I can use in the plesk panel for this?

**Closed** 2021-10-06 16:34 UTC
Labels: enhancement
