### ISSUE TITLE
Simple typo (I think)

### ISSUE THREAD

**Issue by joundso** [blindsidenetworks/scalelite#892] opened 2023-03-01 08:47 UTC
**Describe the bug**
Within [this image](https://github.com/blindsidenetworks/scalelite/blob/master/images/scalelite.png) there might be a typo in two positions: 
`Recording - 2-A / Recording - 3-B` --> 
`Recording - 2-A / Recording - 2-B` (both with **2** as prefix)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/56686638/222089154-6097908f-7379-48f4-8583-83e59cd752f7.png)

**Comment by ffdixon** [comment] 2023-03-01 11:48
Thanks, it's a small bug that we'll fix in an update to the diagram.

**Comment by jfederico** [comment] 2023-04-13 18:45
Well, technically not a bug. The diagram is referencing two recordings with whatever name you like. It happens to follow a pattern but real recordings don't, so. 

As long as the ID under the BBB server matches the one in the recording list, it is correct. In any case it does not affect the idea.

Closing it

**Closed by jfederico** 2023-04-13 18:45 UTC
Labels: bug
